name: osx

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.target == 'arm64' && 'macos-14' || 'macOS-12' }}
    strategy:
      matrix:
        lisp: [sbcl-bin/2.4.0]
        target: [arm64, x86-64]
    environment: SET_VERSION

    steps:
      - uses: actions/checkout@v2
      - name: checkenv
        run: |
          uname -s -m
          brew install autoconf automake
      - name: Build
        env:
          CFLAGS: -mmacosx-version-min=10.9
          CXXFLAGS: -mmacosx-version-min=10.9
          LDFLAGS: -mmacosx-version-min=10.9
        run: |
          gcc -v
          ./bootstrap
          ./configure
          make
          make install
          make pack
          ros install snmsts/sn.github
      - name: Upload
        env:
          GITHUB_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make -f scripts/Makefile latest-version musl-upload
